apiVersion: skaffold/v1alpha2
kind: Config

build:
  artifacts:
  - imageName: gcr.io/gcp-early-access-sandbox/ccweb
    workspace: ./web
  - imageName: gcr.io/gcp-early-access-sandbox/ccworker
    workspace: ./worker

deploy:
  kubectl:
    manifests:
    - k8s/*.yaml

profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: gcp-early-access-sandbox